In [235]:
import numpy as np
def solution(m):
    m = np.rint(np.array(m)).astype(int)
    size=m.shape[0]
    numTermStates=0
#     print(m.shape)
    for i in range(size):
        if not np.any(m[i]):
            numTermStates+=1
            m[i,i]=1
    m_sumAxis=m.sum(axis=1)
    
    m_denom=np.lcm.reduce(m_sumAxis)
#     print("M SUM AXIS:",m_sumAxis,m_denom)
#     //
#     [:, np.newaxis]

    m_numer= m_denom*m/m_sumAxis[:, np.newaxis]
    m_numer=np.rint(m_numer)
#     print(m_numer,numTermStates)
    
    q_numer=m_numer[:size-numTermStates,:size-numTermStates]
    r_numer=m_numer[:size-numTermStates,size-numTermStates:]
    q_denom=r_denom=m_denom
    q_numer,q_denom, q_gcd=normalise(q_numer,q_denom)
    r_numer,r_denom, r_gcd=normalise(r_numer,r_denom)
#     print("q:",q_numer,q_denom)
#     print("r:",r_numer,r_denom)
    
    identity_minus_q_numer= np.identity(q_numer.shape[0])*q_denom-q_numer
    
#     print("i - q:",identity_minus_q_numer)
    N_denom= np.linalg.det(identity_minus_q_numer)
    N_denom= round(N_denom)
    N_numer= np.linalg.inv(identity_minus_q_numer)*N_denom*q_denom
    N_numer= np.rint(N_numer)
    N_numer,N_denom, N_gcd=normalise(N_numer,N_denom)
    
#     print("N:",N_numer,N_denom)
    absorb_numer=np.dot(N_numer,r_numer)[0]
    absorb_denom=round(N_denom*r_denom)
#     print("ABSORB NUMER:",absorb_numer)
#     absorb_test_gcd=np.rint(np.append(absorb_numer,absorb_denom)).astype(int)
#     print("test:",absorb_test_gcd)
    absorb_numer,absorb_denom,absorb_gcd = normalise(absorb_numer,absorb_denom)
#     absorb_gcd=np.gcd.reduce(absorb_test_gcd)
#     absorb_numer=absorb_numer/absorb_gcd
#     absorb_denom=absorb_denom/absorb_gcd
#     print("absorb numer:",absorb_numer,absorb_gcd,absorb_denom)
    
    aslist=np.rint(absorb_numer).astype(int).tolist()
    aslist.append(int(round(absorb_denom)))
    return aslist
        
def normalise(numer,denom):
#     numer=np.rint(numer)
#     denom=round(denom)
    test_gcd=np.append(numer,denom).astype(int)
    gcd=np.gcd.reduce(test_gcd)
    numer=numer/gcd
    denom=denom//gcd
    return numer,denom,gcd
    

    
    

In [233]:
normalise(np.array([256,120]),4)

(array([64., 30.]), 1, 4)

In [240]:
solution([[0, 2, 1, 0, 0], [0, 0, 0, 3, 4], [0, 0, 0, 0, 0], [0, 0, 0, 0,0], [0, 0, 0, 0, 0]])a

(5, 5)
[[0.         0.66666667 0.33333333 0.         0.        ]
 [0.         0.         0.         0.42857143 0.57142857]
 [0.         0.         1.         0.         0.        ]
 [0.         0.         0.         1.         0.        ]
 [0.         0.         0.         0.         1.        ]] 3
q: [[0.         0.66666667]
 [0.         0.        ]]
r: [[0.33333333 0.         0.        ]
 [0.         0.42857143 0.57142857]]
[[ 1.         -0.66666667]
 [ 0.          1.        ]]
[[1.         0.66666667]
 [0.         1.        ]]
absorb probrabs: [[0.33333333 0.28571429 0.38095238]
 [0.         0.42857143 0.57142857]]


[7, 6, 8, 21]

In [239]:
solution([[0, 2, 2, 0, 0], [0, 0, 0, 2, 2], [0, 0, 0, 0, 0], [0, 0, 0, 0,0], [0, 0, 0, 0, 0]])

(5, 5)
[[0.  0.5 0.5 0.  0. ]
 [0.  0.  0.  0.5 0.5]
 [0.  0.  1.  0.  0. ]
 [0.  0.  0.  1.  0. ]
 [0.  0.  0.  0.  1. ]] 3
q: [[0.  0.5]
 [0.  0. ]]
r: [[0.5 0.  0. ]
 [0.  0.5 0.5]]
[[ 1.  -0.5]
 [ 0.   1. ]]
[[1.  0.5]
 [0.  1. ]]
absorb probrabs: [[0.5  0.25 0.25]
 [0.   0.5  0.5 ]]


[2, 1, 1, 4]

In [241]:
solution([[1,1,0,0],[0,1,1,0],[1,0,0,1],[0,0,0,0]])

(4, 4)
[[0.5 0.5 0.  0. ]
 [0.  0.5 0.5 0. ]
 [0.5 0.  0.  0.5]
 [0.  0.  0.  1. ]] 1
q: [[0.5 0.5 0. ]
 [0.  0.5 0.5]
 [0.5 0.  0. ]]
r: [[0. ]
 [0. ]
 [0.5]]
[[ 0.5 -0.5  0. ]
 [ 0.   0.5 -0.5]
 [-0.5  0.   1. ]]
[[4. 4. 2.]
 [2. 4. 2.]
 [2. 2. 2.]]
absorb probrabs: [[1.]
 [1.]
 [1.]]


[1, 1]

In [223]:
solution([[0, 1, 203, 0, 0, 1]
          , [20, 0, 100, 3, 2, 0]
          , [4, 34, 12, 0, 3, 0]
          , [0, 0, 0, 0, 0, 0]
          , [0, 0, 0, 0, 0, 0]
          , [0, 0, 0, 0, 0, 0]])

(6, 6)
M SUM AXIS: [2 9 1 1 1 1] 18
[[ 0.  9.  0.  0.  0.  9.]
 [ 8.  0.  0.  6.  4.  0.]
 [ 0.  0. 18.  0.  0.  0.]
 [ 0.  0.  0. 18.  0.  0.]
 [ 0.  0.  0.  0. 18.  0.]
 [ 0.  0.  0.  0.  0. 18.]] 4
q: [[0. 9.]
 [8. 0.]] 18.0
r: [[0. 0. 0. 9.]
 [0. 6. 4. 0.]] 18.0
i - q: [[18. -9.]
 [-8. 18.]]
N: [[18.  9.]
 [ 8. 18.]] 14.0
ABSORB NUMER: [  0.  54.  36. 162.]
test: 18
absorb numer: [0. 3. 2. 9.] 18 14.0


[0, 3, 2, 9, 14]

In [140]:
import numpy as np
def solution(m):
    m = np.array(m).astype(int)
    size=m.shape[0]
    numTermStates=0
#     print(m.shape)
    for i in range(size):
        if not np.any(m[i]):
            numTermStates+=1
            m[i,i]=1
    m_sumAxis=m.sum(axis=1)
    
    m_denom=np.lcm.reduce(m_sumAxis)
#     print("M SUM AXIS:",m_sumAxis,m_denom)
#     //
#     [:, np.newaxis]

    m_numer= m_denom*m/m_sumAxis[:, np.newaxis]
    m_numer=np.rint(m_numer).astype(int)
#     print(m_numer,numTermStates)
    
    q_numer=m_numer[:size-numTermStates,:size-numTermStates]
    r_numer=m_numer[:size-numTermStates,size-numTermStates:]
    q_denom=r_denom=m_denom
#     print("q:",q_numer,q_denom)
#     print("r:",r_numer,r_denom)
    
    identity_minus_q_numer= np.identity(q_numer.shape[0])*q_denom-q_numer
    
#     print("i - q:",identity_minus_q_numer)
    N_denom= np.linalg.det(identity_minus_q_numer)
    N_denom= int(N_denom)
    N_numer= np.linalg.inv(identity_minus_q_numer)*N_denom*q_denom
    N_numer= N_numer.astype(int)
#     print("N:",N_numer,N_denom)
    absorb_numer=np.dot(N_numer,r_numer)[0]
    absorb_denom=int(N_denom*r_denom)
    absorb_numer_gcd=np.gcd.reduce(absorb_numer,absorb_denom)
    absorb_numer=absorb_numer/absorb_numer_gcd
    absorb_denom=absorb_denom/absorb_numer_gcd
    
    aslist=absorb_numer.astype(int).tolist()
    aslist.append(int(absorb_denom))
    return aslist

In [238]:
import numpy as np
def solution(m):
    def nearIntegerArray(m):
        return np.all(np.isclose(m,np.rint(m)))
    m = np.array(m)
    size=m.shape[0]
    numTermStates=0
    print(m.shape)
    for i in range(size):
        if not np.any(m[i]):
            numTermStates+=1
            m[i,i]=1
    m_normed= m/m.sum(axis=1)[:, np.newaxis]
    print(m_normed,numTermStates)
    
    q=m_normed[:size-numTermStates,:size-numTermStates]
    r=m_normed[:size-numTermStates,size-numTermStates:]
    print("q:",q)
    print("r:",r)
    
            
    
    identity_minus_q= np.identity(q.shape[0])-q
    print(identity_minus_q)
    N= np.linalg.inv(identity_minus_q)
    print(N)
    absorbProbs=np.dot(N,r)[0]
    print("absorb probrabs:",np.dot(N,r))
    
    denom=1
    
    while True:
        numerator=absorbProbs*denom
        if nearIntegerArray(numerator):
            aslist=np.rint(numerator).astype(int).tolist()
            aslist.append(denom)
            return aslist
        denom+=1

In [25]:
import numpy as np
def cofactors(A):
#     U,sigma,Vt = np.linalg.svd(A)
#     N = len(sigma)
#     g = np.tile(sigma,N)
#     g[::(N+1)] = 1
#     G = np.diag(-(-1)**N*np.product(np.reshape(g,(N,N)),1)) 
#     return np.rint(U @ G @ Vt).astype(int)
    return np.rint(np.linalg.inv(A)*np.linalg.det(A)).astype(int)

In [9]:
cofactors(np.array([[3,0,2],[2,0,-2],[0,1,1]])).tolist()

[[2.0, -2.0, 2.0], [2.0, 3.0, -3.0], [0.0, 10.0, 0.0]]

In [16]:
cofactors(np.array([[40,23,-3,-39],[19,-34,3,19],[-203,-4,103,23],[635,27,19,8]],dtype= int))

array([[ -65482., -118365.,   18247.,  -90568.],
       [1259938., 2668011.,  -10997., -162712.],
       [-620072., -461846., -619418., -145140.],
       [2418014., 1487569.,   59877., -177684.]])

In [24]:
adjugate(np.array([[403,234,-334,-393],[2090,-90,99,939],[-203,-433,403,23],[635,279,49,88]]))

array([[-124183857,  -45690866,  -86286717,  -44499297],
       [ 174656267,  107473001,  168295912, -410773193],
       [ 109029502,   96143191, -263903553, -470000913],
       [ 281650058,  -64571406,  236008863,  109226873]])

In [30]:
adjugate(np.array([[1403,2734,-1334,-1393,1200],[2090,-9960,9917,9319,1293],[-1203,-1433,1403,2131,1102],[6135,2719,4199,1898,2931],[2301,2913,4991,1001,3919]]))

array([[ -297369586437,  -121618524594,   719249848296, -5031577653963,
         4494652880991],
       [  -28214660824,   291213078550,  -234321723304, -1288828913152,
          877342978206],
       [  233407827506,   366772734658, -7242437662294, -5935756895728,
         5238976460502],
       [  671847268071,   -64604154078,  3926958576636,  1446702240015,
        -4039401593187],
       [-1785282508177,  -440360921606, -1036792836862,  7640810728517,
        -7118600318967]])

In [221]:
import numpy as np
# Best numpy implementation
def solution(m):
    m = np.rint(np.array(m)).astype(int)
    size=m.shape[0]
    numTermStates=0
    print(m.shape)
    for i in range(size):
        if not np.any(m[i]):
            numTermStates+=1
            m[i,i]=1
    m_sumAxis=m.sum(axis=1)
    
    m_denom=np.lcm.reduce(m_sumAxis)
    print("M SUM AXIS:",m_sumAxis,m_denom)
#     //
#     [:, np.newaxis]

    m_numer= m_denom*m/m_sumAxis[:, np.newaxis]
    # m_numer=np.rint(m_numer)
    print(m_numer,numTermStates)
    
    q_numer=m_numer[:size-numTermStates,:size-numTermStates]
    r_numer=m_numer[:size-numTermStates,size-numTermStates:]
    q_denom=r_denom=m_denom
    q_numer,q_denom, q_gcd=normalise(q_numer,q_denom)
    r_numer,r_denom, r_gcd=normalise(r_numer,r_denom)
    print("q:",q_numer,q_denom)
    print("r:",r_numer,r_denom)
    
    identity_minus_q_numer= np.identity(q_numer.shape[0]).astype(int)*q_denom-q_numer
    
    print("i - q:",identity_minus_q_numer)
    N_denom= np.linalg.det(identity_minus_q_numer)
    N_denom= int(round(N_denom))
    N_numer= np.linalg.inv(identity_minus_q_numer)*N_denom*q_denom
    N_numer= np.rint(N_numer).astype(int)
    N_numer,N_denom, N_gcd=normalise(N_numer,N_denom)
    
    print("N:",N_numer,N_denom)
    absorb_numer=np.dot(N_numer,r_numer)[0]
    absorb_denom=N_denom*r_denom
    print("ABSORB NUMER:",absorb_numer)
#     absorb_test_gcd=np.rint(np.append(absorb_numer,absorb_denom)).astype(int)
    
    absorb_numer,absorb_denom,absorb_gcd = normalise(absorb_numer,absorb_denom)
    print("test:",absorb_gcd)
#     absorb_gcd=np.gcd.reduce(absorb_test_gcd)
#     absorb_numer=absorb_numer/absorb_gcd
#     absorb_denom=absorb_denom/absorb_gcd
    print("absorb numer:",absorb_numer,absorb_gcd,absorb_denom)
    
    aslist=absorb_numer.astype(int).tolist()
    aslist.append(int(round(absorb_denom)))
    return aslist
        
def normalise(numer,denom):
#     numer=np.rint(numer)
#     denom=round(denom)
    test_gcd=np.append(numer,denom).astype(int)
    gcd=np.gcd.reduce(test_gcd)
    numer=numer/gcd
    denom=denom/gcd
    return numer,denom,gcd


In [ ]:
import numpy as np
# Best numpy implementation
def solution(m):
    m = np.rint(np.array(m)).astype(int)
    size=m.shape[0]
    numTermStates=0
    print(m.shape)
    for i in range(size):
        if not np.any(m[i]):
            numTermStates+=1
            m[i,i]=1
    m_sumAxis=m.sum(axis=1)
    
    m_denom=np.lcm.reduce(m_sumAxis)
    print("M SUM AXIS:",m_sumAxis,m_denom)
#     //
#     [:, np.newaxis]

    m_numer= m_denom*m/m_sumAxis[:, np.newaxis]
    # m_numer=np.rint(m_numer)
    print(m_numer,numTermStates)
    
    q_numer=m_numer[:size-numTermStates,:size-numTermStates]
    r_numer=m_numer[:size-numTermStates,size-numTermStates:]
    q_denom=r_denom=m_denom
    q_numer,q_denom, q_gcd=normalise(q_numer,q_denom)
    r_numer,r_denom, r_gcd=normalise(r_numer,r_denom)
    print("q:",q_numer,q_denom)
    print("r:",r_numer,r_denom)
    
    identity_minus_q_numer= np.identity(q_numer.shape[0]).astype(int)*q_denom-q_numer
    
    print("i - q:",identity_minus_q_numer)
    N_denom= np.linalg.det(identity_minus_q_numer)
    N_denom= int(round(N_denom))
    N_numer= np.linalg.inv(identity_minus_q_numer)*N_denom*q_denom
    N_numer= np.rint(N_numer).astype(int)
    N_numer,N_denom, N_gcd=normalise(N_numer,N_denom)
    
    print("N:",N_numer,N_denom)
    absorb_numer=np.dot(N_numer,r_numer)[0]
    absorb_denom=N_denom*r_denom
    print("ABSORB NUMER:",absorb_numer)
#     absorb_test_gcd=np.rint(np.append(absorb_numer,absorb_denom)).astype(int)
    
    absorb_numer,absorb_denom,absorb_gcd = normalise(absorb_numer,absorb_denom)
    print("test:",absorb_gcd)
#     absorb_gcd=np.gcd.reduce(absorb_test_gcd)
#     absorb_numer=absorb_numer/absorb_gcd
#     absorb_denom=absorb_denom/absorb_gcd
    print("absorb numer:",absorb_numer,absorb_gcd,absorb_denom)
    
    aslist=absorb_numer.astype(int).tolist()
    aslist.append(int(round(absorb_denom)))
    return aslist
        
def normalise(numer,denom):
#     numer=np.rint(numer)
#     denom=round(denom)
    test_gcd=np.append(numer,denom).astype(int)
    gcd=np.gcd.reduce(test_gcd)
    numer=numer/gcd
    denom=denom/gcd
    return numer,denom,gcd


In [ ]:
import numpy as np
def solution(m):
    m = np.rint(np.array(m)).astype(np.int64)
    size=m.shape[0]
    numTermStates=0
    print_safe(m.shape)
    for i in range(size):
        if not np.any(m[i]):
            numTermStates+=1
            m[i,i]=1
    m_sumAxis=m.sum(axis=1)
    
    m_denom=np.lcm.reduce(m_sumAxis)
    print_safe("M SUM AXIS:",m_sumAxis,m_denom)
#     //
#     [:, np.newaxis]
    m_numer= m_denom*m/m_sumAxis[:, np.newaxis]
    m_numer,m_denom,m_gcd=normalise(m_numer,m_denom)
    print_safe(m_numer,numTermStates)
    
    q_numer=m_numer[:size-numTermStates,:size-numTermStates]
    r_numer=m_numer[:size-numTermStates,size-numTermStates:]
    q_denom=r_denom=m_denom
    q_numer,q_denom, q_gcd=normalise(q_numer,q_denom)
    r_numer,r_denom, r_gcd=normalise(r_numer,r_denom)
    print_safe("q:",q_numer,q_denom)
    print_safe("r:",r_numer,r_denom)
    
    identity_minus_q_numer= np.identity(q_numer.shape[0],dtype=np.int64)*q_denom-q_numer
    identity_minus_q_numer,identity_minus_q_denom,identity_minus_q_gcd= normalise(identity_minus_q_numer,q_denom)
    
    print_safe("i - q:",identity_minus_q_numer)
    N_denom= int(round(np.linalg.det(identity_minus_q_numer)))
    # print_safe("ADJUGATE APPROX:",np.linalg.inv(identity_minus_q_numer)*N_denom)
    # print_safe("ADJUGATE PRECISE:",np.rint(np.linalg.inv(identity_minus_q_numer)*N_denom).astype(int))
    # print_safe("Error:",np.rint(np.linalg.inv(identity_minus_q_numer)*N_denom)-np.linalg.inv(identity_minus_q_numer)*N_denom)
    float_adjugate=np.linalg.inv(identity_minus_q_numer)*N_denom
    adjugate=np.rint(float_adjugate).astype(np.int64)
    print_safe("Error",adjugate-float_adjugate)
    N_numer= adjugate*identity_minus_q_denom
    # N_denom=sp.Matrix(identity_minus_q_numer).determinant()
    # N_numer=sp.Matrix(identity_minus_q_numer).adjugate()*q_denom
    # Writing a more precise 

    N_numer,N_denom, N_gcd=normalise(N_numer,N_denom)
    print_safe("N:",N_numer,N_numer.dtype,N_gcd,N_denom)
    absorb_numer=np.dot(N_numer,r_numer)[0]

    absorb_denom=long(N_denom)*r_denom
    print_safe("denoms:",N_denom,r_denom,"->",absorb_denom)
    
#     absorb_test_gcd=np.rint(np.append(absorb_numer,absorb_denom)).astype(int)
    
    absorb_numer,absorb_denom,absorb_gcd = normalise(absorb_numer,absorb_denom)
    # print_safe("test:",absorb_gcd)
#     absorb_gcd=np.gcd.reduce(absorb_test_gcd)
#     absorb_numer=absorb_numer/absorb_gcd
#     absorb_denom=absorb_denom/absorb_gcd
    print_safe("absorb numer:",absorb_numer,absorb_gcd,absorb_denom)
    
    aslist=absorb_numer.astype(np.int64).tolist()
    aslist.append(int(round(absorb_denom)))
    return aslist
        
def normalise(numer,denom):
    # numer=np.rint(numer).astype(int)
#     denom=round(denom)
    test_gcd=np.append(numer,denom)
    gcd=np.gcd.reduce(test_gcd)
    numer=numer/gcd
    denom=long(denom//gcd)
    return numer,denom,gcd
  
def print_safe(*args):
  if(True):
    print(args) 
  # 


    # solution([[0, 1, 203, 0, 0, 1]
    #       , [20, 0, 320, 3, 2, 0]
    #       , [4, 34, 12, 0, 3, 0]
    #       , [0, 0, 0, 0, 0, 0]
    #       , [0, 0, 0, 0, 0, 0]
    #       , [0, 0, 0, 0, 0, 0]])